author: Remato
name: trello-integration
description: Integrate Github pull requests with Trello cards
branding:
    color: yellow
    icon: link
inputs:
    github-token:
        description: Github token, https://docs.github.com/en/actions/reference/authentication-in-a-workflow.
        required: true
    github-require-keyword-prefix:
        description: When set to true, match only URLs prefixed with “Closes” etc. Just like https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword.
        default: false
    github-require-trello-card:
        description: Throw an error if no Trello cards can be found in the PR description.
        default: false
    github-include-pr-comments:
        description: Include PR comments when searching for Trello cards.
        default: true
    github-include-pr-branch-name:
        description: Include PR branch name when searching for Trello cards (e.g. "1234-card-title"). If card idID is found, it automatically comments card URL to the PR.
        default: false
    github-users-to-trello-users:
        description: |-
            Newline-separated list of mapping between Github username and Trello username. Example:
            map-github-users-to-trello: |-
              GithubUser1:TrelloUser1
              GithubUser2:TrelloUser2
    trello-api-key:
        description: Trello API key, visit https://trello.com/app-key for key.
        required: true
    trello-auth-token:
        description: Trello auth token, visit https://trello.com/app-key then click generate a token.
        required: true
    trello-organization-name:
        description: Your organization name to avoid assigning cards to outside members. Edit your workspace details and look for the short name.
    trello-board-id:
        description: Trello board ID where to move the cards.
    trello-list-id-pr-draft:
        description: Trello list ID for draft pull request.
    trello-list-id-pr-open:
        description: Trello list ID for open pull request.
    trello-list-id-pr-closed:
        description: Trello list ID for closed pull request.
    trello-add-labels-to-cards:
        description: Enable or disable the automatic addition of labels to cards.
        default: true
    trello-conflicting-labels:
        description: When a card has one of these labels, branch category label is not assigned.
    trello-card-position:
        description: Position of the card after being moved to a list. Can be "top" or "bottom".
        default: 'top'
    trello-remove-unrelated-members:
        description: Enable or disable the removal of unrelated users on trello cards.
        default: true
runs:
    using: node20
    main: 'dist/index.js'
