author: Remato
name: trello-integration
description: GitHub Action to integrate Github pull requests with Trello cards
branding:
    color: yellow
    icon: anchor
inputs:
    github-token:
        description: Github token, https://docs.github.com/en/actions/reference/authentication-in-a-workflow
        required: true
    github-require-keyword-prefix:
        description: When true match only URLs prefixed with “Closes” etc just like https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
        default: false
    github-require-trello-card:
        description: Throw an error if no Trello cards can be found in the PR description
        default: false
    trello-api-key:
        description: Trello API key, visit https://trello.com/app-key for key
        required: true
    trello-auth-token:
        description: Trello auth token, visit https://trello.com/app-key then click generate a token
        required: true
    trello-organization-name:
        description: Your organization name to avoid assigning cards to outside members, edit your workspace details and look for the short name
    trello-board-id:
        description: Trello board ID where to move the cards
    trello-list-id-pr-draft:
        description: Trello list ID for draft pull request
    trello-list-id-pr-open:
        description: Trello list ID for open pull request
    trello-list-id-pr-closed:
        description: Trello list ID for closed pull request
    trello-conflicting-labels:
        description: When a card has one of these labels then branch category label is not assigned
    trello-card-in-branch-name:
        description: When true search for card name (e.g. "1234-card-title") in the branch name if card URL is not found in PR description or comments. If card id is found from branch then adds a comment with the card URL.
        default: false
runs:
    using: node20
    main: 'dist/index.js'
